# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67c4791ad011910f008eff34d57dc233ce3c52027790d39d3b16412bed42c310f0d90d52d757541790362dda32753142802056d17dac02d60f55efa39e2f344a

test:
  secret_key_base: 11c2eebe5dd8c0ec26c1afb851b48f1f5e301e113a6b03c2bc0fc7052571e044f796f3e6edaf5bbf2911fa65e9bbdca06d54bfb593f8038ec911468fab09a8ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
